name: Apoorv Srivastava
description: Executive Trainee (TPL)
avatar: "/assets/images/Apoorv_home.jpg"

footer-links:
  email: apoorv9600@gmail.com
  github: apoorv-s
  linkedin: apoorv-sri
  twitter: ap00rv_sri
  